// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjfknDt_rgyD0Jo132Od3fJrTNC8enQw',
    appId: '1:431981162280:web:9ff48c7220df9b07c92a1d',
    messagingSenderId: '431981162280',
    projectId: 'studentproject-3eb54',
    authDomain: 'studentproject-3eb54.firebaseapp.com',
    databaseURL: 'https://studentproject-3eb54-default-rtdb.firebaseio.com',
    storageBucket: 'studentproject-3eb54.appspot.com',
    measurementId: 'G-PN4M0G585L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNd8TaBABZJ5EN6tf4_ypeYpH5QDCDag',
    appId: '1:431981162280:android:172637e66bfa9b9ec92a1d',
    messagingSenderId: '431981162280',
    projectId: 'studentproject-3eb54',
    databaseURL: 'https://studentproject-3eb54-default-rtdb.firebaseio.com',
    storageBucket: 'studentproject-3eb54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgPBYCxgHUy-oEvABjkfDZjYtOFZ0sns',
    appId: '1:431981162280:ios:6115f7aa95976bf3c92a1d',
    messagingSenderId: '431981162280',
    projectId: 'studentproject-3eb54',
    databaseURL: 'https://studentproject-3eb54-default-rtdb.firebaseio.com',
    storageBucket: 'studentproject-3eb54.appspot.com',
    iosClientId: '431981162280-qrgtdonc2tgo2e9cste739jh0tfm1nev.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtgPBYCxgHUy-oEvABjkfDZjYtOFZ0sns',
    appId: '1:431981162280:ios:6115f7aa95976bf3c92a1d',
    messagingSenderId: '431981162280',
    projectId: 'studentproject-3eb54',
    databaseURL: 'https://studentproject-3eb54-default-rtdb.firebaseio.com',
    storageBucket: 'studentproject-3eb54.appspot.com',
    iosClientId: '431981162280-qrgtdonc2tgo2e9cste739jh0tfm1nev.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
